---
title:
timezone: UTC
exclude:
  - tina
collections:
  posts:
    title: Posts
    output: true
  pages:
    title: Pages
    output: true
  settings:
    title: Settings
    output: true
tagline:
description:
contact:
baseurl: "/aidens-jekyll-boilerplate"
picture:
  source: "assets/uploads"
  output: "assets/generated-images"
  suppress_warnings: true
