---
title: aidensymes.com-2020
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  -
title:
tagline: 
description: 
contact: 
